spring:
  application:
    name: estoque-relogios
  datasource:
    url: jdbc:mysql://localhost:3306/gerenciamento_estoque
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update