spring:
  application:
    name: estoque-relogios
  datasource:
    url: jdbc:mysql://mysql-81358b9-projetointegrador.c.aivencloud.com:25899/gerenciamento_estoque
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
