spring:
  application:
    name: estoque-relogios
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  private:
    key: "classpath:chave_privada.key"
  public:
    key: "classpath:chave_publica.pub"